Pandas : Pandas is a library for python programming language for data manipulation and data analysis. It offers data structure and operations for manipulating numerical table and time series .

In [1]:
#Pandas program to create and display a one-dimensional array-like object containing an array of data.
import pandas as pd
onedarr = pd.Series([1,2,3,4,5])
onedarr

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
#Pandas program to convert a Panda module Series to Python list and it’s type.
import pandas as pd
a = pd.Series([1,2,3,4,5])
print(a)
print(type(a))
print(a.tolist())
print(type(a.tolist()))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
#Pandas program to add, subtract, multiple and divide two Pandas Series.
import pandas as pd
series1 = pd.Series([1,2,3,4])
series2 = pd.Series([2,3,4,5])
print(series1)
print(series2)
print("add: " , series1+series2)
print("substract: ", series1 - series2)
print("multiply: ", series1 * series2)
print("divide: ", series1 / series2)

0    1
1    2
2    3
3    4
dtype: int64
0    2
1    3
2    4
3    5
dtype: int64
add:  0    3
1    5
2    7
3    9
dtype: int64
substract:  0   -1
1   -1
2   -1
3   -1
dtype: int64
multiply:  0     2
1     6
2    12
3    20
dtype: int64
divide:  0    0.500000
1    0.666667
2    0.750000
3    0.800000
dtype: float64


In [5]:
#Pandas Program to compare the element of two pandas series
import pandas as pd
series1 = pd.Series([1,2,3,4])
series2 = pd.Series([5,4,3,2])
print("comparing the elemnt of two pandas series: ")
print(series1 == series2)
print(series1 > series2)
print(series1 < series2)
print(series1 >= series2)
print(series1 <= series2)

comparing the elemnt of two pandas series: 
0    False
1    False
2     True
3    False
dtype: bool
0    False
1    False
2    False
3     True
dtype: bool
0     True
1     True
2    False
3    False
dtype: bool
0    False
1    False
2     True
3     True
dtype: bool
0     True
1     True
2     True
3    False
dtype: bool


In [8]:
#Pandas program to convert a dictionary to a Pandas series.
import pandas as pd
dict_ = {'a': 1 , 'b': 2 , 'c': 3, 'd': 4}
print(dict_)
dicttoPs = pd.Series(dict_)
print(dicttoPs)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}
a    1
b    2
c    3
d    4
dtype: int64


In [9]:
#Pandas program to convert a NumPy array to a Pandas series.
import numpy as np
import pandas as pd

array = np.array([1,2,3,4])
print(array)
array_series = pd.Series(array)
print(array_series)

[1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int32


In [16]:
# Pandas program to change the data type of given a column or a Series.
import pandas as pd
series = pd.Series(['1','2','pandas','3.0'])
print(series)
print('\n\n')
print(pd.to_numeric(series, errors = 'coerce'))

0         1
1         2
2    pandas
3       3.0
dtype: object



0    1.0
1    2.0
2    NaN
3    3.0
dtype: float64


In [24]:
#Pandas program to convert the first column of a DataFrame as a Series.
import pandas as pd
d = {'column1': [1,2,3,4], "column2": [3,4,5,6], "column3": [7,8,9,10]}
df = pd.DataFrame(data = d)
print("orignal data frame")
print(df)
print('\n')
s1 = df.iloc[: , 0]
print('first column of data frame to series')
print(s1)

orignal data frame
   column1  column2  column3
0        1        3        7
1        2        4        8
2        3        5        9
3        4        6       10


first column of data frame to series
0    1
1    2
2    3
3    4
Name: column1, dtype: int64


In [32]:
#Pandas program to convert a given Series to an array.
import pandas as pd
import numpy as np

series = pd.Series([1,2,3,4,'python'])
print(series)
array = np.array(series.values.tolist())
print(array)

0         1
1         2
2         3
3         4
4    python
dtype: object
['1' '2' '3' '4' 'python']


In [38]:
#Pandas program to convert Series of lists to one Series.
import pandas as pd
list_series = pd.Series([['red','orange','blue'],['red','black'],['yellow']])
print(list_series)
print('\n')
print('converting series of list to one series')
one_series = list_series.apply(pd.Series).stack().reset_index(drop = True)
print(one_series)

0    [red, orange, blue]
1           [red, black]
2               [yellow]
dtype: object


converting series of list to one series
0       red
1    orange
2      blue
3       red
4     black
5    yellow
dtype: object


In [47]:
#Pandas program to sort a given Series
import pandas as pd
s = pd.Series(['1','2','3','4','5','sangam','6','7'])
print(s)
print('\n')
new_s = pd.Series(s).sort_values()
print(new_s)

0         1
1         2
2         3
3         4
4         5
5    sangam
6         6
7         7
dtype: object


0         1
1         2
2         3
3         4
4         5
6         6
7         7
5    sangam
dtype: object


In [51]:
#python program to add some data to existing series
import pandas as pd
s = pd.Series([1,2,3])
print(s)
print("\n")
print("adding data to existing series")
new_s = s.append(pd.Series(['san',3]))
print(new_s)

0    1
1    2
2    3
dtype: int64


adding data to existing series
0      1
1      2
2      3
0    san
1      3
dtype: object


In [54]:
#Pandas program to create a subset of a given series based on value and condition.
import pandas as pd
s = pd.Series([1,2,3,4,5,6,7,8,9])
print(s)
print('\n')
new_s = s[:-3]
print(new_s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [59]:
#Pandas program to change the order of index of a given series.
import pandas as pd
s = pd.Series(data = [1,2,3,4,5] , index = ['A','B','C','D','E'])
print(s)
print('\n')
new_s = s.reindex(index = ['D','A','B','E','C'])
print(new_s)

A    1
B    2
C    3
D    4
E    5
dtype: int64


D    4
A    1
B    2
E    5
C    3
dtype: int64


In [61]:
#Pandas program to create the mean and standard deviation of the data of a given Series.
import pandas as pd
s = pd.Series([1,2,3,4,5])
print(s)
print("mean: ", s.mean())
print("standard deviation: " , s.std())


0    1
1    2
2    3
3    4
4    5
dtype: int64
mean:  3.0
standard deviation:  1.5811388300841898


In [67]:
#Pandas program to get the items of a given series not present in another given series.
import pandas as pd
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([3,4,5,6])
print(s1)
print(s2)
print(s1[~s1.isin(s2)])

0    1
1    2
2    3
3    4
dtype: int64
0    3
1    4
2    5
3    6
dtype: int64
0    1
1    2
dtype: int64


In [84]:
#Write a Pandas program to get the items which are not common of two given series.
import pandas as pd
import numpy as np
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([2,4,6,8,10,12,14,16,18])
sr1 = pd.Series(np.union1d(s1,s2))
print(sr1 , '\n')
sr2 = pd.Series(np.intersect1d(s1,s2))
print(sr2, '\n')
print("printing the itmes which are not common of two given series \n")
result = sr1[~sr1.isin(sr2)]
print(result)


0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    12
11    14
12    16
13    18
dtype: int64 

0     2
1     4
2     6
3     8
4    10
dtype: int64 

printing the itmes which are not common of two given series 

0      1
2      3
4      5
6      7
8      9
10    12
11    14
12    16
13    18
dtype: int64


In [97]:
#Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series
import pandas as pd
import numpy as np
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(5,3,10))
print("orignal series")
print(num_series)
result = np.percentile(num_series , q= [0,25,50,75,100])
print(result)

orignal series
0   -0.249296
1    6.028041
2    8.459107
3    4.242692
4    7.943962
5    6.542657
6    5.663539
7    1.789870
8    4.431513
9    5.765004
dtype: float64
[-0.24929642  4.28989704  5.71427167  6.4140027   8.45910741]


In [96]:
import pandas as pd
import numpy as np
num_state = np.random.RandomState(2)
num_series = pd.Series(num_state.normal(5, 3, 10))
print("Original Series:")
print(num_series)
result = np.percentile(num_series, q=[0, 25, 50, 75, 100])
print("\nMinimum, 25th percentile, median, 75th, and maximum of a given series:")
print(result)

Original Series:
0    3.749726
1    4.831200
2   -1.408588
3    9.920812
4   -0.380307
5    2.474758
6    6.508644
7    1.264136
8    1.826143
9    2.272977
dtype: float64

Minimum, 25th percentile, median, 75th, and maximum of a given series:
[-1.40858829  1.40463764  2.37386753  4.56083125  9.92081243]
