NUMPY : Numpy is a library for python programming langauge which add supports of multidimensional arrays and matrices. It have large collection of mathematical function to operate on these arrays.

In [2]:
import numpy as np

In [3]:
#check numpy version
numpy.__version__

'1.18.5'

In [5]:
#how to get help on add function using numpy
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [8]:
#program to check whether none of the element of given array is zero.
#np.all() : all of the element is none zero
#np.any() : any pf the element is non zero
x  = np.array([1,2,3,4])
y = np.array([1,2,3,4,0])
print(np.all(x))
print(np.all(y))

True
False


In [9]:
x = np.array([1,0,0,0])
y = np.array([0,0,0,0])
print(np.any(x))
print(np.any(y))

True
False


In [10]:
#NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

import numpy as np
a = np.array([1,0,np.nan, np.inf])
print(a)
print(np.isfinite(a))

[ 1.  0. nan inf]
[ True  True False False]


In [12]:
# NumPy program to test element-wise for positive or negative infinity.
a = np.array([1, 0, np.nan , np.inf])
print(a)
print(np.isinf(a))

[ 1.  0. nan inf]
[False False False  True]


In [13]:
#numpy program to test element wise for nan
a = np.array([1, 0, np.nan , np.inf])
print(a)
print(np.isnan(a))

[ 1.  0. nan inf]
[False False  True False]


In [14]:
#NumPy program to test element-wise for complex number, real number of a given array.
#Also test whether a given number is a scalar type or not.
#Scalar is the single element of a number feild.

a = np.array([1+2j , 2-3j , 1 ,2 , np.nan , np.inf])
print("checking complex: " , np.iscomplex(a))
print("checking real: ", np.isreal(a))
print("checking scalar: ", np.isscalar(3))
print("checking scalar: ", np.isscalar([3]))

checking complex:  [ True  True False False False False]
checking real:  [False False  True  True  True  True]
checking scalar:  True
checking scalar:  False


# NumPy program to test whether two arrays are element-wise equal within a tolerance.
numpy.allclose() function is used to find if two arrays are element-wise equal within a tolerance. 
The tolerance values are positive, typically very small numbers. 
The relative difference (rtol * abs(arr2)) and the absolute difference atol are 
added together to compare against the absolute difference between arr1 and arr2. 
If either array contains one or more NaNs, False is returned.
Infs are treated as equal if they are in the same place and of the same sign in both arrays.

If the following equation is element-wise True, then allclose returns True.
absolute(arr1 - arr2) <= (atol + rtol * absolute(arr2))
As, The above equation is not symmetric in arr1 and arr2, So, allclose(arr1, arr2) might be different from allclose(arr2, arr1) in some rare cases.

In [15]:
import numpy as np
  
# input arrays
in_arr1 = np.array([5e5, 1e-7, 4.000004e6])
print ("1st Input array : ", in_arr1) 
  
in_arr2 = np.array([5.00001e5, 1e-7, 4e6])
print ("2nd Input array : ", in_arr2) 
  
# setting the absolute and relative tolerance
rtol = 1e-05
atol = 1e-08
  
res = np.allclose(in_arr1, in_arr2, rtol, atol)
print ("Are the two arrays are equal within the tolerance: \t", res)

1st Input array :  [5.000000e+05 1.000000e-07 4.000004e+06]
2nd Input array :  [5.00001e+05 1.00000e-07 4.00000e+06]
Are the two arrays are equal within the tolerance: 	 True


In [26]:
import numpy as np
print(np.allclose([1,2,3] , [1,2,3]))
print(np.allclose([1,np.nan , 3], [1, np.nan , 3]))
print(np.allclose([1,np.nan , 3] , [1, np.nan , 3], equal_nan = True))

True
False
True


In [32]:
#NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays
import numpy as np
x  = np.array([1,2,3])
y = np.array([2,2,1])
print(np.greater(x , y))
print(np.greater_equal(x , y))
print(np.less(x,y))
print(np.less_equal(x,y))

[False False  True]
[False  True  True]
[ True False False]
[ True  True False]


In [33]:
#NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given array.
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x,y))
print(np.allclose(x,y))

[ True  True  True  True  True  True  True  True  True False]
True


In [42]:
# NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
x = np.array([1,7,13,105])
print("the size of the memory occupied by the said array is: " ,x.size * x.itemsize)

the size of the memory occupied by the said array is:  16


In [44]:
#NumPy program to create an array of 10 zeros, 10 ones, 10 fives.
import numpy as np
array1 = np.zeros(10)
array2 = np.ones(10)
array3 = np.ones(10)*5
print(array1)
print(array2)
print(array3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [49]:
#NumPy program to create an array of the integers from 30 to70.
import numpy as np
array = np.arange(30,71)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [50]:
#NumPy program to create an array of all the even integers from 30 to 70.
import numpy as np
array = np.arange(30, 71, 2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [56]:
#NumPy program to create a 3x3 identity matrix.
import numpy as np
array = np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [133]:
#NumPy program to generate a random number between 0 and 1.
import numpy as np
from numpy import random
array = random.rand()
array

0.5327209552935761

In [184]:
random.randint(100)

53

In [239]:
#NumPy program to generate an array of 15 random numbers from a standard normal distribution.
np.random.normal(5,50,15)

array([ 50.80757766,   9.93942084, -70.48002464,  56.25408772,
        15.47138766,   9.65159533,  49.97933384,  20.50374107,
        49.1976859 ,  32.96211672, -58.3219981 , 102.20451905,
         4.74155176,  31.31225464, -24.82473437])

In [198]:
#NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

import numpy as np 
array = np.arange(15,56)
print(array)
print("\n")
print(array[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [208]:
# NumPy program to create a 3X4 array using and iterate over it.

import numpy as n
a = np.arange(10,22).reshape((3, 4))
print(a)
for i in np.nditer(a):
    print(i ,  end  =" ")

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
10 11 12 13 14 15 16 17 18 19 20 21 

In [212]:
#NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

import numpy as np
from numpy import random
array = random.randint(5 , 50 , size =(10))
print(array)

[19 49 43 13 21 40 25 14  6 26]


In [223]:
array = np.linspace(5,50,10)
array

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [238]:
#NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
array = np.arange(0,20)
print(array , "\n")
array[(array >= 9) & (array <= 15)] *= -1
print(array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [250]:
#NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
import numpy as np
from numpy import random

x = random.randint(0,11,5)
print(x)

[ 3 10  1  7  4]


In [252]:
#NumPy program to multiply the values of two given vectors.

import numpy as np
x = np.array([1,2,3,4])
y = np.random.randint(5,25,4)
print(x)
print(y)
print(x * y)

[1 2 3 4]
[ 5  8 23 19]
[ 5 16 69 76]


In [253]:
#NumPy program to multiply the values of two given vectors.

x = np.arange(5,14).reshape(3,3)
y = np.arange(0,3).reshape(3,1)
print(x)
print("\n")
print(y)
print("\n")
print(x * y)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


[[0]
 [1]
 [2]]


[[ 0  0  0]
 [ 8  9 10]
 [22 24 26]]


In [267]:
#NumPy program to create a 3x4 matrix filled with values from 10 to 21
import numpy as np
x = np.random.randint(10,22,size = (12)).reshape(3,4)
print(x)

[[17 21 17 18]
 [20 10 12 17]
 [13 21 19 16]]


In [268]:
x = np.arange(10,22).reshape(3,4)
print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [272]:
#NumPy program to find the number of rows and columns of a given matrix.
np.shape(x)

(3, 4)

In [275]:
#NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0. 
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [276]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [286]:
#NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0. 
x = np.ones((10,10))
print(x)
print("\n\n")
x[1:-1 , 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [292]:
#NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5
import numpy as np
x = np.zeros((5,5))
print(x)
print("\n\n")
x = np.diag([1,2,3,4,5])
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]



[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [296]:
#NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
import numpy as np
x = np.zeros((4,4))
print(x , "\n\n")
x[::2 , 1::2] = 1
x[1::2 , ::2] = 1
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
